// <auto-generated />
using System;
using Intervu.Infrastructure.Persistence.SqlServer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intervu.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(IntervuDbContext))]
    partial class IntervuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewerCompanies", b =>
                {
                    b.Property<int>("InterviewerProfilesId")
                        .HasColumnType("int");

                    b.Property<int>("CompaniesId")
                        .HasColumnType("int");

                    b.HasKey("InterviewerProfilesId", "CompaniesId");

                    b.HasIndex("CompaniesId");

                    b.ToTable("InterviewerCompanies", (string)null);

                    b.HasData(
                        new
                        {
                            InterviewerProfilesId = 2,
                            CompaniesId = 1
                        },
                        new
                        {
                            InterviewerProfilesId = 2,
                            CompaniesId = 4
                        },
                        new
                        {
                            InterviewerProfilesId = 2,
                            CompaniesId = 10
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            CompaniesId = 8
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            CompaniesId = 3
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            CompaniesId = 6
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            CompaniesId = 7
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            CompaniesId = 9
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            CompaniesId = 2
                        });
                });

            modelBuilder.Entity("InterviewerSkills", b =>
                {
                    b.Property<int>("InterviewerProfilesId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("InterviewerProfilesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("InterviewerSkills", (string)null);

                    b.HasData(
                        new
                        {
                            InterviewerProfilesId = 2,
                            SkillsId = 1
                        },
                        new
                        {
                            InterviewerProfilesId = 2,
                            SkillsId = 7
                        },
                        new
                        {
                            InterviewerProfilesId = 2,
                            SkillsId = 11
                        },
                        new
                        {
                            InterviewerProfilesId = 2,
                            SkillsId = 12
                        },
                        new
                        {
                            InterviewerProfilesId = 2,
                            SkillsId = 13
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            SkillsId = 3
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            SkillsId = 4
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            SkillsId = 12
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            SkillsId = 9
                        },
                        new
                        {
                            InterviewerProfilesId = 5,
                            SkillsId = 14
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            SkillsId = 3
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            SkillsId = 4
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            SkillsId = 5
                        },
                        new
                        {
                            InterviewerProfilesId = 6,
                            SkillsId = 15
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoPath = "logos/google.png",
                            Name = "Google",
                            Website = "https://google.com"
                        },
                        new
                        {
                            Id = 2,
                            LogoPath = "logos/meta.png",
                            Name = "Meta",
                            Website = "https://meta.com"
                        },
                        new
                        {
                            Id = 3,
                            LogoPath = "logos/amazon.png",
                            Name = "Amazon",
                            Website = "https://amazon.com"
                        },
                        new
                        {
                            Id = 4,
                            LogoPath = "logos/microsoft.png",
                            Name = "Microsoft",
                            Website = "https://microsoft.com"
                        },
                        new
                        {
                            Id = 5,
                            LogoPath = "logos/netflix.png",
                            Name = "Netflix",
                            Website = "https://netflix.com"
                        },
                        new
                        {
                            Id = 6,
                            LogoPath = "logos/tiktok.png",
                            Name = "TikTok",
                            Website = "https://tiktok.com"
                        },
                        new
                        {
                            Id = 7,
                            LogoPath = "logos/apple.png",
                            Name = "Apple",
                            Website = "https://apple.com"
                        },
                        new
                        {
                            Id = 8,
                            LogoPath = "logos/uber.png",
                            Name = "Uber",
                            Website = "https://uber.com"
                        },
                        new
                        {
                            Id = 9,
                            LogoPath = "logos/spotify.png",
                            Name = "Spotify",
                            Website = "https://spotify.com"
                        },
                        new
                        {
                            Id = 10,
                            LogoPath = "logos/stripe.png",
                            Name = "Stripe",
                            Website = "https://stripe.com"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.HasIndex("StudentId");

                    b.ToTable("Feedbacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AIAnalysis = "{}",
                            Comments = "Great answers and communication.",
                            InterviewerId = 2,
                            Rating = 5,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("VideoCallRoomUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.HasIndex("StudentId");

                    b.ToTable("InterviewRooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 60,
                            InterviewerId = 2,
                            ScheduledTime = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            StudentId = 1,
                            VideoCallRoomUrl = "https://meet.example/room1"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.IntervieweeProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("int");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IntervieweeProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Aspiring backend developer.",
                            CVUrl = "https://example.com/cv-alice.pdf",
                            CurrentAmount = 0,
                            PortfolioUrl = "https://portfolio.example.com/alice",
                            Skills = "[C#, SQL]"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.ToTable("InterviewerAvailabilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2025, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            InterviewerId = 2,
                            IsBooked = false,
                            StartTime = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentAmount")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InterviewerProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Bio = "Senior Backend Engineer with real interview experience",
                            CurrentAmount = 0,
                            ExperienceYears = 8,
                            PortfolioUrl = "https://portfolio.example.com/bob",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Fullstack Engineer previously at Uber",
                            CurrentAmount = 0,
                            ExperienceYears = 6,
                            PortfolioUrl = "https://portfolio.example.com/john",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Senior Frontend Engineer focusing on UI/UX interviews",
                            CurrentAmount = 0,
                            ExperienceYears = 7,
                            PortfolioUrl = "https://portfolio.example.com/sarah",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Welcome to Intervu platform",
                            Title = "Welcome"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.NotificationReceive", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId", "ReceiverId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("NotificationReceives", (string)null);

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            ReceiverId = 1
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InterviewRoomId")
                        .HasColumnType("int");

                    b.Property<int>("IntervieweeId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InterviewRoomId");

                    b.HasIndex("IntervieweeId");

                    b.HasIndex("InterviewerId");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50.00m,
                            InterviewRoomId = 1,
                            IntervieweeId = 1,
                            InterviewerId = 2,
                            PaymentMethod = "Card",
                            Status = 0,
                            TransactionDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 5,
                            Name = "React"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 8,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 9,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 11,
                            Name = "System Design"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Machine Learning"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Email = "sarah.lee@example.com",
                            FullName = "Sarah Lee",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FullName = "Alice Student",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FullName = "Bob Interviewer",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin@example.com",
                            FullName = "Admin",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("InterviewerCompanies", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewerSkills", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.IntervieweeProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewRoom", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Intervu.Domain.Entities.IntervieweeProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Intervu.Domain.Entities.IntervieweeProfile", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Intervu.Domain.Entities.IntervieweeProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerAvailability", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerProfile", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Intervu.Domain.Entities.InterviewerProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intervu.Domain.Entities.NotificationReceive", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewRoom", null)
                        .WithMany()
                        .HasForeignKey("InterviewRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.IntervieweeProfile", null)
                        .WithMany()
                        .HasForeignKey("IntervieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
