// <auto-generated />
using System;
using Intervu.Infrastructure.Persistence.PostgreSQL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intervu.Infrastructure.Persistence.PostgreSQL.Migrations
{
    [DbContext(typeof(IntervuPostgreDbContext))]
    [Migration("20251221165252_AddPasswordResetToken")]
    partial class AddPasswordResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewerCompanies", b =>
                {
                    b.Property<Guid>("InterviewerProfilesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompaniesId")
                        .HasColumnType("uuid");

                    b.HasKey("InterviewerProfilesId", "CompaniesId");

                    b.HasIndex("CompaniesId");

                    b.ToTable("InterviewerCompanies", (string)null);

                    b.HasData(
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            CompaniesId = new Guid("11111111-1111-4111-8111-111111111111")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            CompaniesId = new Guid("44444444-4444-4444-8444-444444444444")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            CompaniesId = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            CompaniesId = new Guid("88888888-8888-4888-8888-888888888888")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            CompaniesId = new Guid("33333333-3333-4333-8333-333333333333")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            CompaniesId = new Guid("66666666-6666-4666-8666-666666666666")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            CompaniesId = new Guid("77777777-7777-4777-8777-777777777777")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            CompaniesId = new Guid("99999999-9999-4999-8999-999999999999")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            CompaniesId = new Guid("22222222-2222-4222-8222-222222222222")
                        });
                });

            modelBuilder.Entity("InterviewerSkills", b =>
                {
                    b.Property<Guid>("InterviewerProfilesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillsId")
                        .HasColumnType("uuid");

                    b.HasKey("InterviewerProfilesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("InterviewerSkills", (string)null);

                    b.HasData(
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            SkillsId = new Guid("b1b1b1b1-b1b1-41b1-81b1-b1b1b1b1b1b1")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            SkillsId = new Guid("02020202-0202-4202-8202-020202020202")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            SkillsId = new Guid("06060606-0606-4606-8606-060606060606")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            SkillsId = new Guid("07070707-0707-4707-8707-070707070707")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            SkillsId = new Guid("08080808-0808-4808-8808-080808080808")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            SkillsId = new Guid("d3d3d3d3-d3d3-43d3-83d3-d3d3d3d3d3d3")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            SkillsId = new Guid("e4e4e4e4-e4e4-44e4-84e4-e4e4e4e4e4e4")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            SkillsId = new Guid("07070707-0707-4707-8707-070707070707")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            SkillsId = new Guid("04040404-0404-4404-8404-040404040404")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            SkillsId = new Guid("09090909-0909-4909-8909-090909090909")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            SkillsId = new Guid("d3d3d3d3-d3d3-43d3-83d3-d3d3d3d3d3d3")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            SkillsId = new Guid("e4e4e4e4-e4e4-44e4-84e4-e4e4e4e4e4e4")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            SkillsId = new Guid("f5f5f5f5-f5f5-45f5-85f5-f5f5f5f5f5f5")
                        },
                        new
                        {
                            InterviewerProfilesId = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            SkillsId = new Guid("0a0a0a0a-0a0a-4a0a-8a0a-0a0a0a0a0a0a")
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            LogoPath = "logos/google.png",
                            Name = "Google",
                            Website = "https://google.com"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            LogoPath = "logos/meta.png",
                            Name = "Meta",
                            Website = "https://meta.com"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333333"),
                            LogoPath = "logos/amazon.png",
                            Name = "Amazon",
                            Website = "https://amazon.com"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-8444-444444444444"),
                            LogoPath = "logos/microsoft.png",
                            Name = "Microsoft",
                            Website = "https://microsoft.com"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-4555-8555-555555555555"),
                            LogoPath = "logos/netflix.png",
                            Name = "Netflix",
                            Website = "https://netflix.com"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-4666-8666-666666666666"),
                            LogoPath = "logos/tiktok.png",
                            Name = "TikTok",
                            Website = "https://tiktok.com"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-4777-8777-777777777777"),
                            LogoPath = "logos/apple.png",
                            Name = "Apple",
                            Website = "https://apple.com"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-4888-8888-888888888888"),
                            LogoPath = "logos/uber.png",
                            Name = "Uber",
                            Website = "https://uber.com"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-4999-8999-999999999999"),
                            LogoPath = "logos/spotify.png",
                            Name = "Spotify",
                            Website = "https://spotify.com"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            LogoPath = "logos/stripe.png",
                            Name = "Stripe",
                            Website = "https://stripe.com"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterviewerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InterviewRoomId")
                        .IsUnique();

                    b.HasIndex("InterviewerId");

                    b.HasIndex("StudentId");

                    b.ToTable("Feedbacks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a0b1c2d-e3f4-4a5b-8c9d-0e1f2a3b4c10"),
                            AIAnalysis = "{}",
                            Comments = "Great answers and communication.",
                            InterviewRoomId = new Guid("5c5d6e7f-9a8b-4d3c-8e9b-7c6d5e4f3a66"),
                            InterviewerId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            Rating = 5,
                            StudentId = new Guid("0d0b8b1e-2e2c-43e2-9d8e-7d2f7a2a1a11")
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewBookingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid>("InterviewerAvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InterviewBookingTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e8f9a0b-c1d2-4e3f-8a9b-0c1d2e3f4a88"),
                            Amount = 1000,
                            InterviewerAvailabilityId = new Guid("6d7e8f9a-b8a9-4c3d-8f9e-6d5c4b3a2a77"),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("0d0b8b1e-2e2c-43e2-9d8e-7d2f7a2a1a11")
                        },
                        new
                        {
                            Id = new Guid("8f9a0b1c-d2e3-4f5a-9b0c-1d2e3f4a5b99"),
                            Amount = 500,
                            InterviewerAvailabilityId = new Guid("6d7e8f9a-b8a9-4c3d-8f9e-6d5c4b3a2a77"),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22")
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InterviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCodes")
                        .HasColumnType("text");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProblemShortName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestCases")
                        .HasColumnType("text");

                    b.Property<string>("VideoCallRoomUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.HasIndex("StudentId");

                    b.ToTable("InterviewRooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c5d6e7f-9a8b-4d3c-8e9b-7c6d5e4f3a66"),
                            DurationMinutes = 60,
                            InterviewerId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            ScheduledTime = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            StudentId = new Guid("0d0b8b1e-2e2c-43e2-9d8e-7d2f7a2a1a11"),
                            VideoCallRoomUrl = "https://meet.example/room1"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CVUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("CurrentAmount")
                        .HasColumnType("integer");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CandidateProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d0b8b1e-2e2c-43e2-9d8e-7d2f7a2a1a11"),
                            Bio = "Aspiring backend developer.",
                            CVUrl = "https://example.com/cv-alice.pdf",
                            CurrentAmount = 0,
                            PortfolioUrl = "https://portfolio.example.com/alice",
                            Skills = "[C#, SQL]"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InterviewerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.ToTable("InterviewerAvailabilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d7e8f9a-b8a9-4c3d-8f9e-6d5c4b3a2a77"),
                            EndTime = new DateTime(2025, 11, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            InterviewerId = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            IsBooked = false,
                            StartTime = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankBinNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CurrentAmount")
                        .HasColumnType("integer");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InterviewerProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            BankAccountNumber = "",
                            BankBinNumber = "",
                            Bio = "Senior Backend Engineer with real interview experience",
                            CurrentAmount = 0,
                            ExperienceYears = 8,
                            PortfolioUrl = "https://portfolio.example.com/bob",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            BankAccountNumber = "",
                            BankBinNumber = "",
                            Bio = "Fullstack Engineer previously at Uber",
                            CurrentAmount = 0,
                            ExperienceYears = 6,
                            PortfolioUrl = "https://portfolio.example.com/john",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            BankAccountNumber = "",
                            BankBinNumber = "",
                            Bio = "Senior Frontend Engineer focusing on UI/UX interviews",
                            CurrentAmount = 0,
                            ExperienceYears = 7,
                            PortfolioUrl = "https://portfolio.example.com/sarah",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-4a6b-8c9d-0e1f2a3b4c20"),
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Welcome to Intervu platform",
                            Title = "Welcome"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.NotificationReceive", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId", "ReceiverId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("NotificationReceives", (string)null);

                    b.HasData(
                        new
                        {
                            NotificationId = new Guid("0a1b2c3d-4e5f-4a6b-8c9d-0e1f2a3b4c20"),
                            ReceiverId = new Guid("0d0b8b1e-2e2c-43e2-9d8e-7d2f7a2a1a11")
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-41b1-81b1-b1b1b1b1b1b1"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("c2c2c2c2-c2c2-42c2-82c2-c2c2c2c2c2c2"),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("d3d3d3d3-d3d3-43d3-83d3-d3d3d3d3d3d3"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("e4e4e4e4-e4e4-44e4-84e4-e4e4e4e4e4e4"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("f5f5f5f5-f5f5-45f5-85f5-f5f5f5f5f5f5"),
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("01010101-0101-4101-8101-010101010101"),
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("02020202-0202-4202-8202-020202020202"),
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("03030303-0303-4303-8303-030303030303"),
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = new Guid("04040404-0404-4404-8404-040404040404"),
                            Name = "AWS"
                        },
                        new
                        {
                            Id = new Guid("05050505-0505-4505-8505-050505050505"),
                            Name = "Azure"
                        },
                        new
                        {
                            Id = new Guid("06060606-0606-4606-8606-060606060606"),
                            Name = "System Design"
                        },
                        new
                        {
                            Id = new Guid("07070707-0707-4707-8707-070707070707"),
                            Name = "Microservices"
                        },
                        new
                        {
                            Id = new Guid("08080808-0808-4808-8808-080808080808"),
                            Name = "Docker"
                        },
                        new
                        {
                            Id = new Guid("09090909-0909-4909-8909-090909090909"),
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = new Guid("0a0a0a0a-0a0a-4a0a-8a0a-0a0a0a0a0a0a"),
                            Name = "Machine Learning"
                        });
                });

            modelBuilder.Entity("Intervu.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a7b6c5d-7e6f-4d3c-9b8a-7c6d5e4f3b44"),
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("4b6c5d7e-8f7a-4c3d-9e8b-6d5c4f3e2a55"),
                            Email = "sarah.lee@example.com",
                            FullName = "Sarah Lee",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0d0b8b1e-2e2c-43e2-9d8e-7d2f7a2a1a11"),
                            Email = "alice@example.com",
                            FullName = "Alice Student",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1e9f9d3b-5b4c-4f1d-9f3a-8b8c3e2d4c22"),
                            Email = "bob@example.com",
                            FullName = "Bob Interviewer",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2f8c7a6b-6d5e-4e2f-8c7a-9d6e5c4b3a33"),
                            Email = "admin@example.com",
                            FullName = "Admin",
                            Password = "10000.QdMM6/umqXH7gdmWhCSo6A==.vfa//iQ7atLzzEXuLQLrQa2+MkrJeouJdN/Bxs81Blo=",
                            Role = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("InterviewerCompanies", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewerSkills", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewRoom", null)
                        .WithOne()
                        .HasForeignKey("Intervu.Domain.Entities.Feedback", "InterviewRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewBookingTransaction", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewRoom", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Intervu.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Intervu.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Intervu.Domain.Entities.CandidateProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerAvailability", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.InterviewerProfile", null)
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.InterviewerProfile", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Intervu.Domain.Entities.InterviewerProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intervu.Domain.Entities.NotificationReceive", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Intervu.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Intervu.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Intervu.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
